CREATE TABLE IF NOT EXISTS "user"
(
    id        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email     TEXT  NOT NULL UNIQUE,
    pass_hash BYTEA NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_email ON "user" (email);

CREATE TABLE IF NOT EXISTS app
(
    id     INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name   TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL UNIQUE
);